### ISSUE TITLE
Link error when compiling gles3 branch

### ISSUE THREAD

**Issue by TheSpydog** [kakashidinho/metalangle#7]
I'm trying to use the standard (non-Xcode) compilation process for building ANGLE, but I'm hitting an error I'm not sure how to work around. I've followed the Dev Setup instructions with both the `gles3` and `gles3-dev` branches, and in both cases, the ninja build is almost complete when this appears:

```
ninja: Entering directory `out/Debug'
[2256/2266] LINK ./angle_perftests
FAILED: angle_perftests 
TOOL_VERSION=1586137043 ../../build/toolchain/mac/linker_driver.py -Wcrl,strippath,/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip ../../third_party/llvm-build/Release+Asserts/bin/clang++ -B /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/  -Wl,-fatal_warnings -stdlib=libc++ -arch x86_64 -segprot PROTECTED_MEMORY rw r -Werror -isysroot ../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.13 -Wl,-ObjC -Wl,-rpath,@loader_path/. -Wl,-rpath,@loader_path/../../.. -o "./angle_perftests" -Wl,-filelist,"./angle_perftests.rsp" ./libangle_util.dylib -framework IOKit -framework CoreFoundation -framework CoreGraphics -framework OpenGL
Undefined symbols for architecture x86_64:
  "angle::IsMetalRendererAvailable()", referenced from:
      angle::IsConfigWhitelisted(angle::SystemInfo const&, angle::PlatformParameters const&) in angle_test_instantiate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "../../build/toolchain/mac/linker_driver.py", line 287, in <module>
    Main(sys.argv)
  File "../../build/toolchain/mac/linker_driver.py", line 97, in Main
    subprocess.check_call(compiler_driver_args, env=env)
  File "/usr/local/Cellar/python@2/2.7.17/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../../third_party/llvm-build/Release+Asserts/bin/clang++', '-B', '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/', '-Wl,-fatal_warnings', '-stdlib=libc++', '-arch', 'x86_64', '-segprot', 'PROTECTED_MEMORY', 'rw', 'r', '-Werror', '-isysroot', '../../../../../../../Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk', '-mmacosx-version-min=10.13', '-Wl,-ObjC', '-Wl,-rpath,@loader_path/.', '-Wl,-rpath,@loader_path/../../..', '-o', './angle_perftests', '-Wl,-filelist,./angle_perftests.rsp', './libangle_util.dylib', '-framework', 'IOKit', '-framework', 'CoreFoundation', '-framework', 'CoreGraphics', '-framework', 'OpenGL']' returned non-zero exit status 1
[2257/2266] LINK ./angle_end2end_tests
ninja: build stopped: subcommand failed.
```
Any ideas? Thanks!

**Comment by kakashidinho** [comment]
oh, sorry, I have never run full angle project build before. angle_perftests is one of the executables that I haven't used from angle project. Hence there are some linking errors when building it.
For now, please just use "ninja -C <out directory> angle_end2end_tests" or "ninja -C <out dir> angle_deqp_gles3_tests". It will generate libGLESv2 and libEGL dylib in the <out directory>. Despite its name, libGLESv2 does contain GLES3 stuffs.

I will fix the linking errors in the mean time.

**Comment by kakashidinho** [comment]
This issue is fixed. Thanks for trying out the gles3 branch. If you see any more issues, pls don't hesitate to report them. Thanks.
